import { TicketTemplate } from "./types";

// Hardcoded templates for now - could be moved to database later
export const TICKET_TEMPLATES: Partial<TicketTemplate>[] = [
  {
    id: "Appraisal_Template",
    name: "Appraisal",
    description: "Template for managing property appraisals",
    title: "Appraisal - [Property Address]",
    ticketDescription:
      "Appraisal needed for property at [Address].\n\nAppraisal type:\n[ ] Full appraisal\n[ ] Drive-by appraisal\n[ ] Desktop appraisal\n\nPreferred dates/times:\n- \n\nContact person:\n- Name: \n- Phone: \n- Email:\n\nAdditional notes:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Contact appraisal vendor",
      "Confirm vendor requirements",
      "Schedule appraisal date/time",
      "Notify property owner/tenant",
      "Confirm pets are secured",
      "Arrange for access to property",
      "Confirm appraisal appointment",
      "Follow up post-appraisal",
    ],
  },
  {
    id: "Client_Complaint_Template",
    name: "Client Complaint",
    description: "Template for handling client complaints",
    title: "Client Complaint - [Client Name]",
    ticketDescription:
      "Client complaint received.\n\nClient: \nDate of incident: \n\nNature of complaint:\n\nDetails:\n\nClient's desired resolution:\n\nPriority level: \n\nAssigned to:",
    urgency: "HIGH",
    isActive: true,
    todos: [
      "Review complaint details",
      "Contact client for more information",
      "Investigate the issue",
      "Propose a resolution",
      "Follow up with client",
      "Document the complaint and resolution",
    ],
  },
  {
    id: "Contract_Issue_Template",
    name: "Contract Issue",
    description: "Template for urgent contract-related issues",
    title: "URGENT: Contract Issue - [Property/Client]",
    ticketDescription:
      "Urgent issue with contract for [Property/Client].\n\nIssue type:\n[ ] Missing signatures\n[ ] Incorrect terms\n[ ] Deadline approaching\n[ ] Other: \n\nDetails:\n\nDeadline: \n\nAction needed:",
    urgency: "HIGH",
    isActive: true,
    todos: [
      "Identify contract issue",
      "Contact relevant parties",
      "Draft necessary amendments",
      "Obtain required signatures",
      "Confirm resolution of issue",
    ],
  },
  {
    id: "Document_Request_Template",
    name: "Document Request",
    description: "Template for document requests",
    title: "Document Request - [Document Type]",
    ticketDescription:
      "Document request from [Requester].\n\nDocuments needed:\n[ ] Purchase agreement\n[ ] Disclosure forms\n[ ] Inspection reports\n[ ] Title documents\n[ ] Other: \n\nRequired by: \nPurpose: \n\nDelivery method:\n[ ] Email\n[ ] Physical copy\n[ ] Upload to portal",
    urgency: "LOW",
    isActive: true,
    todos: [
      "Identify documents needed",
      "Contact requester for clarification",
      "Gather documents",
      "Deliver documents as requested",
      "Confirm receipt with requester",
    ],
  },
  {
    id: "Inspection_Scheduling_Template",
    name: "Inspection Scheduling",
    description: "Template for scheduling property inspections",
    title: "Schedule Inspection - [Property Address]",
    ticketDescription:
      "Inspection needed for property at [Address].\n\nInspection type:\n[ ] Home inspection\n[ ] Pest inspection\n[ ] Appraisal\n[ ] Other: \n\nPreferred dates/times:\n- \n\nContact person:\n- Name: \n- Phone: \n- Email:\n\nAdditional notes:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Contact inspection company",
      "Schedule inspection date/time",
      "Notify property owner/tenant",
      "Arrange for access to property",
      "Confirm inspection appointment",
      "Follow up post-inspection",
    ],
  },
  {
    id: "Maintenance_Request_Template",
    name: "Maintenance Request",
    description: "Template for property maintenance requests",
    title: "Maintenance Request - [Property Address]",
    ticketDescription:
      "Maintenance request for property.\n\nProperty: \nTenant/Owner: \n\nIssue description:\n\nUrgency:\n[ ] Emergency (immediate)\n[ ] Urgent (24-48 hours)\n[ ] Routine (within a week)\n\nAccess instructions:\n\nPreferred service window:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Identify maintenance issue",
      "File maintenance report",
      "Contact approved vendor",
      "Schedule maintenance appointment",
      "Confirm appointment with property owner/tenant",
      "Confirm pets are secured",
      "Follow up with vendor",
      "Follow up with property owner/tenant",
      "Confirm work completed",
      "Close maintenance request",
    ],
  },
  {
    id: "Employee_Onboarding_Template",
    name: "Employee Onboarding",
    description: "Template for onboarding new employees",
    title: "Onboarding  - [Employee Name]",
    ticketDescription:
      "New employee onboarding process.\n\nEmployee Name: \nPosition: \nStart Date: \nMarket Center:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Admin: Create Conductor account",
      "Set up workstation",
      "Set up company email and software access",
      "Schedule orientation sessions",
      "Schedule training sessions",
      "Complete training modules",
      "Complete HR paperwork: taxes, direct deposit, benefits, etc.",
      "Review company policies, culture, and values",
      "Review team structure and key contacts",
      "Review job-specific tools and software",
      "Review role-specific procedures, responsibilities, expectations, etc.",
    ],
  },
  {
    id: "New_Listing_Template",
    name: "New Listing",
    description: "Template for setting up a new property listing",
    title: "Setup New Listing - [Property Address]",
    ticketDescription:
      "New listing to be set up.\n\nProperty details:\n- Address: \n- Price: \n- Bedrooms: \n- Bathrooms: \n- Square feet: \n\nTasks needed:\n[ ] Photography scheduled\n[ ] MLS entry\n[ ] Marketing materials\n[ ] Sign installation\n[ ] Open house planning\n\nTarget go-live date:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Gather property details",
      "Schedule photography",
      "Create MLS listing",
      "Plan open house events",
      "Request marketing materials",
      "Install signage",
    ],
  },
  {
    id: "Showing_Request_Template",
    name: "Showing Request",
    description: "Template for scheduling property showings",
    title: "Property Showing Request - [Property Address]",
    ticketDescription:
      "Client wants to schedule a showing for the property at [Address].\n\nPreferred dates/times:\n- \n\nClient contact:\n- Name: \n- Phone: \n- Email: \n\nAdditional notes:",
    urgency: "MEDIUM",
    isActive: true,
    todos: [
      "Confirm date/time with client",
      "Schedule reminders",
      "Notify seller's/buyer's agent",
      "Notify tenants/property owner",
      "Arrange for lockbox/key access",
      "Arrange for pets to be secured",
      "Clean/Stage property if needed",
      "Follow up post-showing",
    ],
  },
  {
    id: "Vendor_Onboarding_Template",
    name: "Vendor Onboarding",
    description: "Template for onboarding new vendors",
    title: "Vendor Onboarding - [Vendor Name]",
    ticketDescription:
      "Onboarding new vendor: [Vendor Name].\n\nServices provided:\n\nContact person:\n- Name: \n- Phone: \n- Email: \n\nRequired documentation:\n[ ] W-9 form\n[ ] Insurance certificates\n[ ] Service agreements\n\nSetup tasks:",
    urgency: "LOW",
    isActive: true,
    todos: [
      "Collect vendor information",
      "Obtain required documentation",
      "Set up vendor in payment system",
      "Review service agreements",
      "Schedule introductory meeting",
    ],
  },
];
