import {
  AssignedTicketNotificationProps,
  CategoryAssignmentProps,
  CreatedTicketNotificationProps,
  MarketCenterAssignmentProps,
  NewCommentNotificationProps,
  SurveyResultsProps,
  TicketSurveyProps,
  UpdatedTicketProps,
} from "@/emails/types";
import type { NotificationCategory, NotificationChannel } from "../types";

type VariablePlaceholders<T> = {
  [K in keyof T]: T[K] extends object
    ? VariablePlaceholders<T[K]> // recursive for nested structures
    : `{{${Extract<K, string>}}}`;
};

export const NotificationTemplateVariables = {
  MarketCenterAssignmentProps: {
    userUpdate: "{{userUpdate}}",
    marketCenterName: "{{marketCenterName}}",
    marketCenterId: "{{marketCenterId}}",
    userName: "{{userName}}",
    editorName: "{{editorName}}",
    editorEmail: "{{editorEmail}}",
  } satisfies VariablePlaceholders<MarketCenterAssignmentProps>,
  CategoryAssignmentProps: {
    userUpdate: "{{userUpdate}}",
    categoryName: "{{categoryName}}",
    categoryDescription: "{{categoryDescription}}",
    marketCenterName: "{{marketCenterName}}",
    marketCenterId: "{{marketCenterId}}",
    userName: "{{userName}}",
    editorName: "{{editorName}}",
    editorEmail: "{{editorEmail}}",
  } satisfies VariablePlaceholders<CategoryAssignmentProps>,
  CreatedTicketNotificationProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    creatorName: "{{creatorName}}",
    creatorId: "{{creatorId}}",
    createdOn: "{{createdOn}}",
    dueDate: "{{dueDate}}",
    assigneeId: "{{assigneeId}}",
    assigneeName: "{{assigneeName}}",
  } satisfies VariablePlaceholders<CreatedTicketNotificationProps>,
  AssignedTicketNotificationProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    createdOn: "{{createdOn}}",
    updatedOn: "{{updatedOn}}",
    editorName: "{{editorName}}",
    editorId: "{{editorId}}",
    updateType: "{{updateType}}",
    currentAssignment: "{{currentAssignment}}", // rendered as list
    previousAssignment: "{{previousAssignment}}", // rendered as list
  } satisfies VariablePlaceholders<AssignedTicketNotificationProps>,
  UpdatedTicketProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    createdOn: "{{createdOn}}",
    updatedOn: "{{updatedOn}}",
    editorName: "{{editorName}}",
    editorId: "{{editorId}}",
    changedDetails: "{{changedDetails}}", // rendered as list
  } satisfies VariablePlaceholders<UpdatedTicketProps>,
  NewCommentNotificationProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    createdOn: "{{createdOn}}",
    commenterName: "{{commenterName}}",
    commenterId: "{{commenterId}}",
    comment: "{{comment}}",
    isInternal: "{{isInternal}}",
  } satisfies VariablePlaceholders<NewCommentNotificationProps>,

  TicketSurveyProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    surveyorName: "{{surveyorName}}",
  } satisfies VariablePlaceholders<TicketSurveyProps>,
  SurveyResultsProps: {
    ticketNumber: "{{ticketNumber}}",
    ticketTitle: "{{ticketTitle}}",
    staffName: "{{staffName}}",
  } satisfies VariablePlaceholders<SurveyResultsProps>,
} as const;

export const notificationTemplatesDefault = [
  {
    templateName: "Market Center User Added",
    templateDescription: "Sent when a user is added to a Market Center",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Market Center Assignment",
    subject: "Market Center Assignment",
    body: `{{editorName}} added you to {{marketCenterName}}`,
    variables: NotificationTemplateVariables.MarketCenterAssignmentProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Market Center User Removed",
    templateDescription: "Sent when a user is removed from a Market Center",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Market Center Assignment",
    subject: "Market Center Assignment",
    body: `{{editorName}} removed you from {{marketCenterName}}`,
    variables: NotificationTemplateVariables.MarketCenterAssignmentProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Category Assignment - Added",
    templateDescription: "Sent when a user is added to a Ticket Category",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Category Assignment",
    subject: "Category Assignment",
    body: `You will now be automatically assigned to tickets created with {{categoryName}}`,
    variables: NotificationTemplateVariables.CategoryAssignmentProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Category Assignment - Removed",
    templateDescription: "Sent when a user is removed from a Ticket Category",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Category Assignment",
    subject: "Category Assignment",
    body: `You will no longer be automatically assigned to tickets created with {{categoryName}}`,
    variables: NotificationTemplateVariables.CategoryAssignmentProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Created",
    templateDescription: "Sent when a user creates a Ticket",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Created",
    subject: "Ticket Created",
    body: `{{ticketTitle}} was created by {{creatorName}}`,
    variables: NotificationTemplateVariables.CreatedTicketNotificationProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Assignment - Added",
    templateDescription: "Sent when a user is assigned to a Ticket",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Assignment",
    subject: "Ticket Assignment",
    body: `{{ticketTitle}} is now in your queue`,
    variables: NotificationTemplateVariables.AssignedTicketNotificationProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Assignment - Removed",
    templateDescription: "Sent when a user is removed from a Ticket",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Assignment",
    subject: "Ticket Assignment",
    body: `{{ticketTitle}} is no longer in your queue`,
    variables: NotificationTemplateVariables.AssignedTicketNotificationProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Updated",
    templateDescription: "Sent when a user updates a Ticket",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Updated",
    subject: "Ticket Updated",
    body: `The following for "{{ticketTitle}}" has been updated: {{changedDetails}}`,
    variables: NotificationTemplateVariables.UpdatedTicketProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "New Comments on Ticket",
    templateDescription: "Sent when a new comment is added to a Ticket",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "New Comments",
    subject: "New Comment for {{ticketTitle}}",
    body: `{{commenterName}} added a new comment to "{{ticketTitle}}": {{comment}}`,
    variables: NotificationTemplateVariables.NewCommentNotificationProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Survey",
    templateDescription: "Sent to the ticket's creator when marked as resolved",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Survey",
    subject: "Survey for {{ticketTitle}}",
    body: "Please take a moment to provide feedback about your experience",
    variables: NotificationTemplateVariables.TicketSurveyProps,
    isDefault: true,
    isActive: true,
  },
  {
    templateName: "Ticket Survey Results",
    templateDescription:
      "Sent to the ticket's assignee and market center manager(s) when new survey results are available",
    category: "ACTIVITY" as NotificationCategory,
    channel: "IN_APP" as NotificationChannel,
    type: "Ticket Survey Results",
    subject: "Survey Completed for {{ticketTitle}}",
    body: "You may now view the ratings and comments provided by the ticket's creator",
    variables: NotificationTemplateVariables.SurveyResultsProps,
    isDefault: true,
    isActive: true,
  },
];
