import { NotificationCategory, NotificationFrequency } from "../../utils";

export const defaultMarketCenterNotificationPreferences = [
  // ACTIVITY: SUMMARY
  // {
  //   frequency: "DAILY" as NotificationFrequency,
  //   category: "ACTIVITY" as NotificationCategory,
  //   type: "Daily Summary",
  //   email: true,
  //   inApp: true,
  //   push: false,
  //   sms: false,
  // },
  // {
  //   frequency: "WEEKLY" as NotificationFrequency,
  //   category: "ACTIVITY" as NotificationCategory,
  //   type: "Weekly Report",
  //   email: true,
  //   inApp: true,
  //   push: false,
  //   sms: false,
  // },
  // ACTIVITY: TICKETS
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Ticket Created",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Ticket Updated",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Ticket Assignment",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  // { // TODO: re-add mentions later
  //   frequency: "INSTANT",
  //   category: "ACTIVITY",
  //   type: "Mentions",
  //   email: true,
  //   inApp: true,
  //   push: false,
  //   sms: false,
  // },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "New Comments",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Market Center Assignment",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Category Assignment",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Ticket Survey",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
  {
    frequency: "INSTANT" as NotificationFrequency,
    category: "ACTIVITY" as NotificationCategory,
    type: "Ticket Survey Results",
    email: true,
    inApp: true,
    push: false,
    sms: false,
  },
];
